// react-test-app/src/views/home/Home.jsx
import React, {useState} from "react";
import "./Home.css";

function Home(props) {
  let [legenda, setLegenda] = useState("novo teste de parametro");

  function resetLegenda(){
    console.log("click resetLegenda")
    setLegenda("Alterado")
  }

  return (
    <div>
      <h1 className="home">Home React ({props.msg})</h1>
      <h2>{legenda}</h2>
      <input type="text" value={legenda} readOnly />
      <input type="text" value={legenda} onChange={
        function(e) {
          console.log(e.target.value)
          setLegenda(e.target.value)
          //this.legenda = "Alterado"
        }
      } />
      <button onClick={resetLegenda}>Reset Legenda</button>
    </div>
  );
}

export default Home;

// angular-test-app/src/app/views/home/home.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  @Input() 
  msg: string | undefined
  legenda: string = "novo teste de parametros"

  constructor() { 

  }

  ngOnInit(): void {
    this.msg = this.msg + " teste2"
  }

  resetLegenda(): void {
    console.log("click resetLegenda")
    this.legenda = "Alterado"
  }

}

<h1 class="home">home angular! ({{msg}})</h1>
<h2>{{legenda}}</h2>
<input type="text" [value]="legenda">
<input type="text" [(ngModel)]="legenda">
<button (click)="resetLegenda()">Reset Legenda</button>
